name: Build

on:
  push:
    branches:
      - "master"
      
jobs:
  buildlinux:
    name: Linux x64
    runs-on: ubuntu-18.04

    steps:
      - name: Prepare Environment
        run: |
            sudo apt-get install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libxcb-randr0

      - name: Prepare Qt Libraries
        uses: jurplel/install-qt-action@v2

      - name: Clone
        uses: actions/checkout@v2

      - name: Compile
        run: |
          qmake CONFIG+=release PREFIX=/usr SavvyCAN.pro
          make -j`grep -c ^processor /proc/cpuinfo`
          
      - name: Package     
        run: |
          make INSTALL_ROOT=appdir install
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/5/linuxdeployqt-5-x86_64.AppImage"
          chmod a+x linuxdeployqt-5-x86_64.AppImage
          ./linuxdeployqt-5-x86_64.AppImage appdir/usr/share/applications/SavvyCAN.desktop -appimage -extra-plugins=iconengines,platformthemes/libqgtk3.so,canbus

      - uses: actions/upload-artifact@v2
        with:
          name: SavvyCAN-Linux_x64.AppImage
          path: SavvyCAN-x86_64.AppImage
          
